plugins:
  - uses:
      - plugin: https://ubiquity-os-command-query-user-development.ubiquity.workers.dev
        with:
          allowPublicQuery: false
  - uses:
      - plugin: ubiquity-os-marketplace/command-ask@development
        with:
          model: o1-mini
          similarityThreshold: 0.9
          maxTokens: 10000
